name: Sync to Hugging Face

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HG }}
        run: git remote add space https://mudathir:$HF@huggingface.co/spaces/mudathir/demo2
      - name: Push to hub
        env:
          HF: ${{ secrets.HG }}
        run: git push --force https://mudathir:$HF@huggingface.co/spaces/mudathir/demo2
